<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'Laptop',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => 'Laptop',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => 'Dell',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '105',
    'name' => 'Dell',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => 'MSI',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '109',
    'name' => 'MSI',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => 'HP',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 1,
    'id' => '106',
    'name' => 'HP',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => 'Asus',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 1,
    'id' => '104',
    'name' => 'Asus',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => 'Acer',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '107',
    'name' => 'Acer',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => 'Lenovo',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 7,
    'level' => 1,
    'id' => '103',
    'name' => 'Lenovo',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => 'Asus Republic of Gamers',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '100',
    'name' => 'Asus Republic of Gamers',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => 'Macbook',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '108',
    'name' => 'Macbook',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'Điện Thoại',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '13',
    'goods_num' => '1',
    'level' => 0,
    'id' => '2',
    'name' => 'Điện Thoại',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => 'LV Mobile',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '121',
    'name' => 'LV Mobile',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => 'Land Rover',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '118',
    'name' => 'Land Rover',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => 'Xiaomi',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '115',
    'name' => 'Xiaomi',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '112',
    'name' => 'Nokia',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => 'Zono',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '257',
    'name' => 'Zono',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => 'Huawei',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '116',
    'name' => 'Huawei',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => 'Asus (Zenfone)',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '113',
    'name' => 'Asus (Zenfone)',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '110',
    'name' => 'Samsung',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => 'Bavapen',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '120',
    'name' => 'Bavapen',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => 'Arbutus',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '117',
    'name' => 'Arbutus',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => 'Oppo',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '114',
    'name' => 'Oppo',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => 'Hyundai',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '130',
    'name' => 'Hyundai',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => 'Apple (iPhone)',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 1,
    'id' => '111',
    'name' => 'Apple (iPhone)',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'Máy tính bảng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => 'Máy tính bảng',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '128',
    'name' => 'Samsung',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => 'Acer',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '125',
    'name' => 'Acer',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => 'iPad (Apple)',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 1,
    'id' => '122',
    'name' => 'iPad (Apple)',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => 'Haier',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '129',
    'name' => 'Haier',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => 'Lenovo',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '126',
    'name' => 'Lenovo',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => 'Asus',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '123',
    'name' => 'Asus',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => 'KingCom',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '127',
    'name' => 'KingCom',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => 'Huawei',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '124',
    'name' => 'Huawei',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'Sim card',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '48',
    'name' => 'Sim card',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'PC Máy văn phòng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => '3',
    'level' => 0,
    'id' => '8',
    'name' => 'PC Máy văn phòng',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'Máy in',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '29',
    'name' => 'Máy in',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => 'Máy fax',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '30',
    'name' => 'Máy fax',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => 'Máy chiếu',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 1,
    'id' => '31',
    'name' => 'Máy chiếu',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'Máy bộ PC',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '4',
    'name' => 'Máy bộ PC',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => 'Máy quét mã vạch',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '101',
    'name' => 'Máy quét mã vạch',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => 'Bộ lưu điện',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '93',
    'name' => 'Bộ lưu điện',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => 'Máy đếm tiền',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '226',
    'name' => 'Máy đếm tiền',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'Máy hủy tài liệu',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => 'Máy hủy tài liệu',
  ),
  224 => 
  array (
    'cat_id' => '224',
    'cat_name' => 'Máy chấm công',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '224',
    'name' => 'Máy chấm công',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => 'Máy Scan',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '70',
    'name' => 'Máy Scan',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => 'Máy tính tiền',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '94',
    'name' => 'Máy tính tiền',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => 'Máy trợ giảng',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '225',
    'name' => 'Máy trợ giảng',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'Màn hình LCD',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '71',
    'name' => 'Màn hình LCD',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'Phụ kiện',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '17',
    'goods_num' => '2',
    'level' => 0,
    'id' => '5',
    'name' => 'Phụ kiện',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => 'Balo túi xách',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '34',
    'name' => 'Balo túi xách',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'Pin sạc dự phòng',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => 'Pin sạc dự phòng',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => 'Tuxedo',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => 'Tuxedo',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '132',
    'name' => 'Sky',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '133',
    'name' => 'Aukey',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => 'Thẻ nhớ',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => '1',
    'level' => 1,
    'id' => '36',
    'name' => 'Thẻ nhớ',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => 'Kingston',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => 'Kingston',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'Team',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '223',
    'name' => 'Team',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => 'Sandisk',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '138',
    'name' => 'Sandisk',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => 'Adata',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => 'Adata',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => 'Elecom',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '136',
    'name' => 'Elecom',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => 'Transcend',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => 'Transcend',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => 'Tai  nghe',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => '4',
    'level' => 1,
    'id' => '37',
    'name' => 'Tai  nghe',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => 'Maxell',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '260',
    'name' => 'Maxell',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => 'Rapoo',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '168',
    'name' => 'Rapoo',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '164',
    'name' => 'Aukey',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => 'MicroLab',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '169',
    'name' => 'MicroLab',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '166',
    'name' => 'Hãng Khác',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => 'Genius',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '165',
    'name' => 'Genius',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => 'Philips',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '170',
    'name' => 'Philips',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => 'Elecom',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '259',
    'name' => 'Elecom',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 2,
    'id' => '167',
    'name' => 'JVJ',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => 'A4tech',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '163',
    'name' => 'A4tech',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => 'Smartwatch',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => 'Smartwatch',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'USB',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '5',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => 'USB',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => 'Team',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '258',
    'name' => 'Team',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '145',
    'name' => 'Sony',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => 'Lexar',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '142',
    'name' => 'Lexar',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => 'Pendrive',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => 'Pendrive',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => 'Sandisk',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '144',
    'name' => 'Sandisk',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => 'Chuột máy tính',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '10',
    'goods_num' => '9',
    'level' => 1,
    'id' => '39',
    'name' => 'Chuột máy tính',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => 'Rapoo',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '154',
    'name' => 'Rapoo',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '151',
    'name' => 'JVJ',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => 'Dell',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '148',
    'name' => 'Dell',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '155',
    'name' => 'Sky',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => 'Logitech',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '152',
    'name' => 'Logitech',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'Genius',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => 'Genius',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '146',
    'name' => '2Good',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => 'Newmen',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '153',
    'name' => 'Newmen',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => 'Hãng Khác',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => 'A4tech',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '147',
    'name' => 'A4tech',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => 'Loa Nghe nhạc',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => 'Loa Nghe nhạc',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => 'MicroLab',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 2,
    'id' => '181',
    'name' => 'MicroLab',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => 'Creative',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '178',
    'name' => 'Creative',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => 'MicroTek',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '182',
    'name' => 'MicroTek',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => 'JBL',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '179',
    'name' => 'JBL',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => 'Soundmax',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '183',
    'name' => 'Soundmax',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '180',
    'name' => 'JVJ',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '177',
    'name' => '2Good',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'Bàn phím máy tính',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => 'Bàn phím máy tính',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => 'Logitech',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '161',
    'name' => 'Logitech',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => 'Elecom',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '158',
    'name' => 'Elecom',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '162',
    'name' => 'Sky',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => 'Genius',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '159',
    'name' => 'Genius',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => 'A4tech',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '156',
    'name' => 'A4tech',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => 'Rapoo',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '160',
    'name' => 'Rapoo',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => 'Colorsit',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '157',
    'name' => 'Colorsit',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => 'Dây, cáp sạc',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '14',
    'level' => 1,
    'id' => '42',
    'name' => 'Dây, cáp sạc',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '200',
    'name' => 'Hãng Khác',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '197',
    'name' => 'JVJ',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '194',
    'name' => 'Aukey',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '198',
    'name' => 'Sky',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => 'Beston',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '195',
    'name' => 'Beston',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => 'Tuxedo',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '199',
    'name' => 'Tuxedo',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => 'Canon',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '196',
    'name' => 'Canon',
  ),
  193 => 
  array (
    'cat_id' => '193',
    'cat_name' => 'Apple',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '193',
    'name' => 'Apple',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'Ổ cứng',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => '2',
    'level' => 1,
    'id' => '46',
    'name' => 'Ổ cứng',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => 'PNY',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '203',
    'name' => 'PNY',
  ),
  207 => 
  array (
    'cat_id' => '207',
    'cat_name' => 'Transcend',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '207',
    'name' => 'Transcend',
  ),
  204 => 
  array (
    'cat_id' => '204',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '204',
    'name' => 'Samsung',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => 'Apacer',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '201',
    'name' => 'Apacer',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => 'Western Digital',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '208',
    'name' => 'Western Digital',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => 'Sandisk',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '205',
    'name' => 'Sandisk',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => 'Kingston',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '202',
    'name' => 'Kingston',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '209',
    'name' => 'Hãng Khác',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '206',
    'name' => 'Sony',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => 'Ốp lưng điện thoại',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => 'Ốp lưng điện thoại',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => 'RAM máy tính',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '95',
    'name' => 'RAM máy tính',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => 'Patriot',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '213',
    'name' => 'Patriot',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => 'KingMax',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '210',
    'name' => 'KingMax',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => 'Kingston',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '211',
    'name' => 'Kingston',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'G.Skill',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '212',
    'name' => 'G.Skill',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => 'Đế tản nhiệt',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '7',
    'level' => 1,
    'id' => '90',
    'name' => 'Đế tản nhiệt',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'DeepCool',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '214',
    'name' => 'DeepCool',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => 'Miếng dán máy tính bảng',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => 'Miếng dán máy tính bảng',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => 'Loa Bluetooth',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => 'Loa Bluetooth',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '187',
    'name' => 'JVJ',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '184',
    'name' => '2Good',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => 'Moigus',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '191',
    'name' => 'Moigus',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => 'JBL',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '188',
    'name' => 'JBL',
  ),
  185 => 
  array (
    'cat_id' => '185',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '185',
    'name' => 'Aukey',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '192',
    'name' => 'Hãng Khác',
  ),
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '189',
    'name' => 'Sky',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => 'Creative',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '186',
    'name' => 'Creative',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => 'WS',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '190',
    'name' => 'WS',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'Đồ chơi độc lạ',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '26',
    'level' => 1,
    'id' => '52',
    'name' => 'Đồ chơi độc lạ',
  ),
  219 => 
  array (
    'cat_id' => '219',
    'cat_name' => 'Apple',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '219',
    'name' => 'Apple',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'Asus',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '216',
    'name' => 'Asus',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '220',
    'name' => 'Aukey',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => 'Dunhill',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '217',
    'name' => 'Dunhill',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => 'Lexma',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '221',
    'name' => 'Lexma',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => 'Logitech',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '218',
    'name' => 'Logitech',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '215',
    'name' => '2Good',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '222',
    'name' => 'Sky',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => 'Phần mềm',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '66',
    'name' => 'Phần mềm',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => 'Bkav',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '171',
    'name' => 'Bkav',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'Phần mềm Office',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '69',
    'name' => 'Phần mềm Office',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => 'Trend Micro',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '175',
    'name' => 'Trend Micro',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => 'Kaspersky',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '172',
    'name' => 'Kaspersky',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => 'Phần mềm dẫn đường',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '96',
    'name' => 'Phần mềm dẫn đường',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => 'VietMap',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '176',
    'name' => 'VietMap',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'Phần mềm Virus',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '67',
    'name' => 'Phần mềm Virus',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => 'Microsoft',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '173',
    'name' => 'Microsoft',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'Phần mềm Windows',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '68',
    'name' => 'Phần mềm Windows',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => 'Norton',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '174',
    'name' => 'Norton',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'Máy đổi trả',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => 'Máy đổi trả',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'Điện thoại đổi cũ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 1,
    'id' => '49',
    'name' => 'Điện thoại đổi cũ',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => 'Máy tính bảng cũ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '50',
    'name' => 'Máy tính bảng cũ',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => 'Laptop cũ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '131',
    'name' => 'Laptop cũ',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'Sửa chữa thay thế',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => 0,
    'level' => 0,
    'id' => '227',
    'name' => 'Sửa chữa thay thế',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => 'Sửa điện thoại, smartphone',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '244',
    'name' => 'Sửa điện thoại, smartphone',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'Cài đặt phần mềm',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '231',
    'name' => 'Cài đặt phần mềm',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => 'Sửa chữa iPhone',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '250',
    'name' => 'Sửa chữa iPhone',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => 'Sửa máy in,photocopy',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '245',
    'name' => 'Sửa máy in,photocopy',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => 'Thi công hệ thống mạng',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '240',
    'name' => 'Thi công hệ thống mạng',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => 'Sửa Laptop, máy tính bàn',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '234',
    'name' => 'Sửa Laptop, máy tính bàn',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => 'Sửa phụ kiện,linh kiện',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '256',
    'name' => 'Sửa phụ kiện,linh kiện',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => 'Sửa chữa iPad',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '251',
    'name' => 'Sửa chữa iPad',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'Sửa máy tính bảng, tablet',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '248',
    'name' => 'Sửa máy tính bảng, tablet',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => 'Phục hồi, cứu dữ liệu',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '242',
    'name' => 'Phục hồi, cứu dữ liệu',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'Bảo trì hệ thống mạng',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '229',
    'name' => 'Bảo trì hệ thống mạng',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => 'Sửa chữa Macbook',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '253',
    'name' => 'Sửa chữa Macbook',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => 'Sửa chữa thiết bị khác',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '249',
    'name' => 'Sửa chữa thiết bị khác',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'Kỹ thuật số',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => 'Kỹ thuật số',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => 'Máy nghe nhạc MP3',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '53',
    'name' => 'Máy nghe nhạc MP3',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => 'Máy nghi âm',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '54',
    'name' => 'Máy nghi âm',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Máy ảnh KTS',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => 'Máy ảnh KTS',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => 'Máy ảnh DSLR',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => 'Máy ảnh DSLR',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'Máy ảnh du lịch',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '65',
    'name' => 'Máy ảnh du lịch',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'Android TV Box',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '56',
    'name' => 'Android TV Box',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => 'Camera hành trình',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '97',
    'name' => 'Camera hành trình',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => 'Webcam',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '99',
    'name' => 'Webcam',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'Thiết bị mạng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => 'Thiết bị mạng',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'ADSL Wireless Router',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '57',
    'name' => 'ADSL Wireless Router',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'Access Point',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '58',
    'name' => 'Access Point',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'Card mạng',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => 'Card mạng',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'Switch Hub',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '60',
    'name' => 'Switch Hub',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '3G Wireless',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '61',
    'name' => '3G Wireless',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => 'USB 3G',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '62',
    'name' => 'USB 3G',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'USB Wireless',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '63',
    'name' => 'USB Wireless',
  ),
);
?>