<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'Laptop',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'Điện Thoại',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '13',
    'goods_num' => '1',
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'Máy tính bảng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'Sim card',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  4 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'PC Máy văn phòng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => '3',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'Phụ kiện',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '17',
    'goods_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '66',
    'cat_name' => 'Phần mềm',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'Máy đổi trả',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'Sửa chữa thay thế',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'Kỹ thuật số',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'Thiết bị mạng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '105',
    'cat_name' => 'Dell',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  12 => 
  array (
    'cat_id' => '109',
    'cat_name' => 'MSI',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  13 => 
  array (
    'cat_id' => '106',
    'cat_name' => 'HP',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
  ),
  14 => 
  array (
    'cat_id' => '104',
    'cat_name' => 'Asus',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
  ),
  15 => 
  array (
    'cat_id' => '107',
    'cat_name' => 'Acer',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  16 => 
  array (
    'cat_id' => '103',
    'cat_name' => 'Lenovo',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 7,
  ),
  17 => 
  array (
    'cat_id' => '100',
    'cat_name' => 'Asus Republic of Gamers',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '108',
    'cat_name' => 'Macbook',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  19 => 
  array (
    'cat_id' => '121',
    'cat_name' => 'LV Mobile',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  20 => 
  array (
    'cat_id' => '118',
    'cat_name' => 'Land Rover',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  21 => 
  array (
    'cat_id' => '115',
    'cat_name' => 'Xiaomi',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  22 => 
  array (
    'cat_id' => '112',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  23 => 
  array (
    'cat_id' => '257',
    'cat_name' => 'Zono',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '116',
    'cat_name' => 'Huawei',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  25 => 
  array (
    'cat_id' => '113',
    'cat_name' => 'Asus (Zenfone)',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  26 => 
  array (
    'cat_id' => '110',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  27 => 
  array (
    'cat_id' => '120',
    'cat_name' => 'Bavapen',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  28 => 
  array (
    'cat_id' => '117',
    'cat_name' => 'Arbutus',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '114',
    'cat_name' => 'Oppo',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  30 => 
  array (
    'cat_id' => '130',
    'cat_name' => 'Hyundai',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '111',
    'cat_name' => 'Apple (iPhone)',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  32 => 
  array (
    'cat_id' => '128',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  33 => 
  array (
    'cat_id' => '125',
    'cat_name' => 'Acer',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  34 => 
  array (
    'cat_id' => '122',
    'cat_name' => 'iPad (Apple)',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
  ),
  35 => 
  array (
    'cat_id' => '129',
    'cat_name' => 'Haier',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  36 => 
  array (
    'cat_id' => '126',
    'cat_name' => 'Lenovo',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  37 => 
  array (
    'cat_id' => '123',
    'cat_name' => 'Asus',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  38 => 
  array (
    'cat_id' => '127',
    'cat_name' => 'KingCom',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  39 => 
  array (
    'cat_id' => '124',
    'cat_name' => 'Huawei',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  40 => 
  array (
    'cat_id' => '34',
    'cat_name' => 'Balo túi xách',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  41 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'Pin sạc dự phòng',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '36',
    'cat_name' => 'Thẻ nhớ',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => '1',
  ),
  43 => 
  array (
    'cat_id' => '37',
    'cat_name' => 'Tai  nghe',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => '4',
  ),
  44 => 
  array (
    'cat_id' => '91',
    'cat_name' => 'Smartwatch',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'USB',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '5',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '39',
    'cat_name' => 'Chuột máy tính',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '10',
    'goods_num' => '9',
  ),
  47 => 
  array (
    'cat_id' => '40',
    'cat_name' => 'Loa Nghe nhạc',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'Bàn phím máy tính',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '42',
    'cat_name' => 'Dây, cáp sạc',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '14',
  ),
  50 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'Ổ cứng',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => '2',
  ),
  51 => 
  array (
    'cat_id' => '43',
    'cat_name' => 'Ốp lưng điện thoại',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '95',
    'cat_name' => 'RAM máy tính',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '90',
    'cat_name' => 'Đế tản nhiệt',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '7',
  ),
  54 => 
  array (
    'cat_id' => '44',
    'cat_name' => 'Miếng dán máy tính bảng',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '41',
    'cat_name' => 'Loa Bluetooth',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'Đồ chơi độc lạ',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '26',
  ),
  57 => 
  array (
    'cat_id' => '53',
    'cat_name' => 'Máy nghe nhạc MP3',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  58 => 
  array (
    'cat_id' => '54',
    'cat_name' => 'Máy nghi âm',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  59 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Máy ảnh KTS',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'Android TV Box',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  61 => 
  array (
    'cat_id' => '97',
    'cat_name' => 'Camera hành trình',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  62 => 
  array (
    'cat_id' => '99',
    'cat_name' => 'Webcam',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  63 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'ADSL Wireless Router',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  64 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'Access Point',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  65 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'Card mạng',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'Switch Hub',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  67 => 
  array (
    'cat_id' => '61',
    'cat_name' => '3G Wireless',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  68 => 
  array (
    'cat_id' => '62',
    'cat_name' => 'USB 3G',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 2,
  ),
  69 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'USB Wireless',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 2,
  ),
  70 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'Máy in',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  71 => 
  array (
    'cat_id' => '30',
    'cat_name' => 'Máy fax',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  72 => 
  array (
    'cat_id' => '31',
    'cat_name' => 'Máy chiếu',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  73 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'Máy bộ PC',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  74 => 
  array (
    'cat_id' => '101',
    'cat_name' => 'Máy quét mã vạch',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  75 => 
  array (
    'cat_id' => '93',
    'cat_name' => 'Bộ lưu điện',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  76 => 
  array (
    'cat_id' => '226',
    'cat_name' => 'Máy đếm tiền',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  77 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'Máy hủy tài liệu',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '224',
    'cat_name' => 'Máy chấm công',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  79 => 
  array (
    'cat_id' => '70',
    'cat_name' => 'Máy Scan',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  80 => 
  array (
    'cat_id' => '94',
    'cat_name' => 'Máy tính tiền',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  81 => 
  array (
    'cat_id' => '225',
    'cat_name' => 'Máy trợ giảng',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'Màn hình LCD',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  83 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'Điện thoại đổi cũ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  84 => 
  array (
    'cat_id' => '50',
    'cat_name' => 'Máy tính bảng cũ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  85 => 
  array (
    'cat_id' => '131',
    'cat_name' => 'Laptop cũ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '134',
    'cat_name' => 'Tuxedo',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '132',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  88 => 
  array (
    'cat_id' => '133',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  89 => 
  array (
    'cat_id' => '137',
    'cat_name' => 'Kingston',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'Team',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  91 => 
  array (
    'cat_id' => '138',
    'cat_name' => 'Sandisk',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  92 => 
  array (
    'cat_id' => '135',
    'cat_name' => 'Adata',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '136',
    'cat_name' => 'Elecom',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  94 => 
  array (
    'cat_id' => '140',
    'cat_name' => 'Transcend',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '260',
    'cat_name' => 'Maxell',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  96 => 
  array (
    'cat_id' => '168',
    'cat_name' => 'Rapoo',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '164',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  98 => 
  array (
    'cat_id' => '169',
    'cat_name' => 'MicroLab',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  99 => 
  array (
    'cat_id' => '166',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '165',
    'cat_name' => 'Genius',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  101 => 
  array (
    'cat_id' => '170',
    'cat_name' => 'Philips',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '259',
    'cat_name' => 'Elecom',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  103 => 
  array (
    'cat_id' => '167',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  104 => 
  array (
    'cat_id' => '163',
    'cat_name' => 'A4tech',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  105 => 
  array (
    'cat_id' => '258',
    'cat_name' => 'Team',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '145',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '142',
    'cat_name' => 'Lexar',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '143',
    'cat_name' => 'Pendrive',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '144',
    'cat_name' => 'Sandisk',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  110 => 
  array (
    'cat_id' => '154',
    'cat_name' => 'Rapoo',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  111 => 
  array (
    'cat_id' => '151',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  112 => 
  array (
    'cat_id' => '148',
    'cat_name' => 'Dell',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  113 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  114 => 
  array (
    'cat_id' => '152',
    'cat_name' => 'Logitech',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'Genius',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '146',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '153',
    'cat_name' => 'Newmen',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '150',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '147',
    'cat_name' => 'A4tech',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  120 => 
  array (
    'cat_id' => '181',
    'cat_name' => 'MicroLab',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  121 => 
  array (
    'cat_id' => '178',
    'cat_name' => 'Creative',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  122 => 
  array (
    'cat_id' => '182',
    'cat_name' => 'MicroTek',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  123 => 
  array (
    'cat_id' => '179',
    'cat_name' => 'JBL',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  124 => 
  array (
    'cat_id' => '183',
    'cat_name' => 'Soundmax',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  125 => 
  array (
    'cat_id' => '180',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  126 => 
  array (
    'cat_id' => '177',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  127 => 
  array (
    'cat_id' => '187',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  128 => 
  array (
    'cat_id' => '184',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  129 => 
  array (
    'cat_id' => '191',
    'cat_name' => 'Moigus',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  130 => 
  array (
    'cat_id' => '188',
    'cat_name' => 'JBL',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  131 => 
  array (
    'cat_id' => '185',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  132 => 
  array (
    'cat_id' => '192',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  133 => 
  array (
    'cat_id' => '189',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  134 => 
  array (
    'cat_id' => '186',
    'cat_name' => 'Creative',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  135 => 
  array (
    'cat_id' => '190',
    'cat_name' => 'WS',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '200',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  137 => 
  array (
    'cat_id' => '197',
    'cat_name' => 'JVJ',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  138 => 
  array (
    'cat_id' => '194',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  139 => 
  array (
    'cat_id' => '198',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  140 => 
  array (
    'cat_id' => '195',
    'cat_name' => 'Beston',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  141 => 
  array (
    'cat_id' => '199',
    'cat_name' => 'Tuxedo',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  142 => 
  array (
    'cat_id' => '196',
    'cat_name' => 'Canon',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  143 => 
  array (
    'cat_id' => '193',
    'cat_name' => 'Apple',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  144 => 
  array (
    'cat_id' => '161',
    'cat_name' => 'Logitech',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  145 => 
  array (
    'cat_id' => '158',
    'cat_name' => 'Elecom',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '162',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  147 => 
  array (
    'cat_id' => '159',
    'cat_name' => 'Genius',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  148 => 
  array (
    'cat_id' => '156',
    'cat_name' => 'A4tech',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  149 => 
  array (
    'cat_id' => '160',
    'cat_name' => 'Rapoo',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '157',
    'cat_name' => 'Colorsit',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  151 => 
  array (
    'cat_id' => '203',
    'cat_name' => 'PNY',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  152 => 
  array (
    'cat_id' => '207',
    'cat_name' => 'Transcend',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  153 => 
  array (
    'cat_id' => '204',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  154 => 
  array (
    'cat_id' => '201',
    'cat_name' => 'Apacer',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  155 => 
  array (
    'cat_id' => '208',
    'cat_name' => 'Western Digital',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  156 => 
  array (
    'cat_id' => '205',
    'cat_name' => 'Sandisk',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  157 => 
  array (
    'cat_id' => '202',
    'cat_name' => 'Kingston',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  158 => 
  array (
    'cat_id' => '209',
    'cat_name' => 'Hãng Khác',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  159 => 
  array (
    'cat_id' => '206',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  160 => 
  array (
    'cat_id' => '219',
    'cat_name' => 'Apple',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  161 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'Asus',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  162 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'Aukey',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  163 => 
  array (
    'cat_id' => '217',
    'cat_name' => 'Dunhill',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  164 => 
  array (
    'cat_id' => '221',
    'cat_name' => 'Lexma',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  165 => 
  array (
    'cat_id' => '218',
    'cat_name' => 'Logitech',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  166 => 
  array (
    'cat_id' => '215',
    'cat_name' => '2Good',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  167 => 
  array (
    'cat_id' => '222',
    'cat_name' => 'Sky',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  168 => 
  array (
    'cat_id' => '64',
    'cat_name' => 'Máy ảnh DSLR',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'Máy ảnh du lịch',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  170 => 
  array (
    'cat_id' => '171',
    'cat_name' => 'Bkav',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'Phần mềm Office',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  172 => 
  array (
    'cat_id' => '175',
    'cat_name' => 'Trend Micro',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '172',
    'cat_name' => 'Kaspersky',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '96',
    'cat_name' => 'Phần mềm dẫn đường',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  175 => 
  array (
    'cat_id' => '176',
    'cat_name' => 'VietMap',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'Phần mềm Virus',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  177 => 
  array (
    'cat_id' => '173',
    'cat_name' => 'Microsoft',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'Phần mềm Windows',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  179 => 
  array (
    'cat_id' => '174',
    'cat_name' => 'Norton',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'DeepCool',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  181 => 
  array (
    'cat_id' => '213',
    'cat_name' => 'Patriot',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '210',
    'cat_name' => 'KingMax',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '211',
    'cat_name' => 'Kingston',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  184 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'G.Skill',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  185 => 
  array (
    'cat_id' => '244',
    'cat_name' => 'Sửa điện thoại, smartphone',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'Cài đặt phần mềm',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '250',
    'cat_name' => 'Sửa chữa iPhone',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '245',
    'cat_name' => 'Sửa máy in,photocopy',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '240',
    'cat_name' => 'Thi công hệ thống mạng',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  190 => 
  array (
    'cat_id' => '234',
    'cat_name' => 'Sửa Laptop, máy tính bàn',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '256',
    'cat_name' => 'Sửa phụ kiện,linh kiện',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  192 => 
  array (
    'cat_id' => '251',
    'cat_name' => 'Sửa chữa iPad',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'Sửa máy tính bảng, tablet',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '242',
    'cat_name' => 'Phục hồi, cứu dữ liệu',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'Bảo trì hệ thống mạng',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  196 => 
  array (
    'cat_id' => '253',
    'cat_name' => 'Sửa chữa Macbook',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  197 => 
  array (
    'cat_id' => '249',
    'cat_name' => 'Sửa chữa thiết bị khác',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>